### ISSUE TITLE
Doesn't work with latest Moodle

### ISSUE THREAD

**Issue by Petah** [AndyNormore/filemanager#5]

**Comment by advancedsoftwarecanada** [comment]
Ah okay, yes, plugin version.php would need to be updated. I had no intention for this project to stick around for so long. Is it helpful to people? Should I update it?

**Comment by rilcy** [comment]
It would be great that you update your file. I've been working on the FileManager for 1 month and I still can't deal with it.

**Comment by andresmrg** [comment]
I haven't been able to make it work. Moodle can't find the file.

**Comment by garryjable** [comment]
Update it for sure, there are no good examples like this out there.

**Comment by advancedsoftwarecanada** [comment]
Updated for Moodle 4.4.0+

It should work all the way back from Moodle 2.3.9.
